apiVersion: v1
kind: Service
metadata:
  name: {{ template "varnish.fullname" . }}-varnish-proxy
  labels:
    app: {{ template "varnish.fullname" . }}-varnish-proxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    host: "{{ include "varnish.host" .}}"
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.varnishLoadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ template "varnish.fullname" . }}-varnish-proxy
