apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "varnish.fullname" . }}-varnish-proxy
spec:
  replicas: 1
  selector:
    app: {{ template "varnish.fullname" . }}-varnish-proxy
  template:
    metadata:
      name: {{ template "varnish.fullname" . }}-varnish-proxy
      labels:
        app: {{ template "varnish.fullname" . }}-varnish-proxy
    spec:
      volumes:
        - name: varnish-config
          configMap:
            name: {{ template "varnish.fullname" . }}-varnish-config
            items:
              - key: default.vcl
                path: default.vcl
      containers:
      - name: varnish
        image: tripviss/varnish
        env:
        - name: VARNISH_VCL
          value: /etc/varnish/default.vcl
        volumeMounts:
          - name: varnish-config
            mountPath: /etc/varnish/
        ports:
        - containerPort: 80
