apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "varnish.fullname" . }}-varnish-config
  labels:
    app: {{ template "varnish.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  default.vcl: |-
{{ $file := (.Files.Get "config/varnish.vcl") }}
{{ tpl $file . | indent 4 }}
